name: testing gitaction trigger pull request

run-name: ${{ github.event_name }} action
on:
  pull_request:
    types:
      - opened
    branches:
      - master

jobs:
  on_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: |
          echo "test push workflow"