name: testing gitaction trigger workflow dispatch

run-name: ${{ github.event_name }} action
on: workflow_dispatch

jobs:
  on_push:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: |
          echo "test workflow dispatch"